### ISSUE TITLE
Should I ignore the ZeroReturnError?

### ISSUE THREAD

**Issue by sajingeo** [adafruit/io-client-python#19]
This does not always happen, should I just ignore this and continue?

OpenSSL.SSL.ZeroReturnError
Traceback (most recent call last):
  File "./sensor.py", line 51, in presenseHandle
    securityEnable = restClient.receive('Security')
  File "build/bdist.linux-armv6l/egg/Adafruit_IO/client.py", line 106, in receive
  File "build/bdist.linux-armv6l/egg/Adafruit_IO/client.py", line 62, in _get
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 60, in get
    return request('get', url, *_kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 49, in request
    return session.request(method=method, url=url, *_kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 457, in request
    resp = self.send(prep, *_send_kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 606, in send
    r.content
  File "/usr/lib/python2.7/dist-packages/requests/models.py", line 724, in content
    self._content = bytes().join(self.iter_content(CONTENT_CHUNK_SIZE)) or bytes()
  File "/usr/lib/python2.7/dist-packages/requests/models.py", line 653, in generate
    for chunk in self.raw.stream(chunk_size, decode_content=True):
  File "/usr/lib/python2.7/dist-packages/urllib3/response.py", line 256, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "/usr/lib/python2.7/dist-packages/urllib3/response.py", line 186, in read
    data = self._fp.read(amt)
  File "/usr/lib/python2.7/httplib.py", line 573, in read
    s = self.fp.read(amt)
  File "/usr/lib/python2.7/socket.py", line 380, in read
    data = self._sock.recv(left)
  File "/usr/lib/python2.7/dist-packages/urllib3/contrib/pyopenssl.py", line 188, in recv
    data = self.connection.recv(_args, **kwargs)

**Comment by happy-jo** [comment]
@sajingeo Thanks for your comment. You are correct this was a one time occurrence and this has not happened since.
