### ISSUE TITLE
python library receive() returns 400 Bad Request instead of 404 Not Found

### ISSUE THREAD

**Issue by torbinsky** [adafruit/io-client-python#26]
**OS:** Windows 64-bit
**Python Version:** Python 2.7.12
**Traceback (most recent call last):**
```
  File "<stdin>", line 1, in <module>
  File "C:\Python27\lib\site-packages\Adafruit_IO\client.py", line 106, in receive
    return Data.from_dict(self._get(path))
  File "C:\Python27\lib\site-packages\Adafruit_IO\client.py", line 63, in _get
    self._handle_error(response)
  File "C:\Python27\lib\site-packages\Adafruit_IO\client.py", line 56, in _handle_error
    raise RequestError(response)
Adafruit_IO.errors.RequestError: Adafruit IO request failed: 400 Bad Request
```

**Description:**
I've been playing around with the Adafruit IO python library. When testing out the Feed `receive()` method, I was mislead by an HTTP status code that was returned in the traceback. 

As you can see in the output above, I got a *400 Bad Request* status in response to calling `receive()` which initially lead me to believe there must be a bug in the python library as it should not be sending malformed requests to your API. A 400 status code should mean that the request is malformed, not that the resource doesn't exist.

It turned out that I had a typo in my feed name and so the problem was simply the feed I was trying to read from did not exist, but this error caused me to waste time debugging the library instead.

My suggestion is to return a 404 in the event that someone attempts to access a feed that does not exist. This would more closely follow standard REST practices.

**Reproduction Steps:**

- Initialize client with a valid key
- Try to read a feed that doesn't exist. i.e. `client.receive('non-existing-feed')`

**Sample Reproduction Code:**
```
from Adafruit_IO import Client
client = Client('#######')
client.receive('non-existing-feed')
```

**Update:**

I should note that after I ran into this, I initially thought to report this as a bug with the API but I couldn't reproduce using the REST API console at https://io.adafruit.com.

Trying https://io.adafruit.com/api/docs/#!/Data/all it appears that the API is returning a 404 if I try to read all data from a feed that doesn't exist. 

If I try https://io.adafruit.com/api/docs/#!/Data/receive with a non-existing feed name, I get a 200 OK which is also odd. I'm not sure why the python library `receive` call is getting a 400.

So at this point it seems specific to the python client, but is probably an API problem somewhere.

**Comment by torbinsky** [comment]
I apologize, I should have found the appropriate API method called by `receive` in the source code. It turns out the client calls https://io.adafruit.com/api/docs/#!/Data/last. When I try this using the console, I also receive a 400, so this is indeed a problem with the REST API.

I'll report this issue with the main adafruit-io project instead and close this one.
