### ISSUE TITLE
simple.py example fails

### ISSUE THREAD

**Issue by jerryneedell** [adafruit/io-client-python#58]
with adafruit-io 2.0.9  I get the following error for the example in api/simple.py

The error occurs even when the Feed exists

```
pi@gjnpi3p-1:~/projects/adafruitio/examples/api $ python3 simple.py 
Traceback (most recent call last):
  File "simple.py", line 21, in <module>
    aio.send_data('Test', 42)
  File "/home/pi/.local/lib/python3.5/site-packages/Adafruit_IO/client.py", line 117, in send_data
    return self.create_data(feed, Data(value=value))
  File "/home/pi/.local/lib/python3.5/site-packages/Adafruit_IO/client.py", line 203, in create_data
    return Data.from_dict(self._post(path, data._asdict()))
  File "/home/pi/.local/lib/python3.5/site-packages/Adafruit_IO/client.py", line 100, in _post
    self._handle_error(response)
  File "/home/pi/.local/lib/python3.5/site-packages/Adafruit_IO/client.py", line 76, in _handle_error
    raise RequestError(response)
  File "/home/pi/.local/lib/python3.5/site-packages/Adafruit_IO/errors.py", line 40, in __init__
    error_message = self._parse_error(response)
  File "/home/pi/.local/lib/python3.5/site-packages/Adafruit_IO/errors.py", line 46, in _parse_error
    content = json.loads(response.content)
  File "/usr/lib/python3.5/json/__init__.py", line 312, in loads
    s.__class__.__name__))
TypeError: the JSON object must be str, not 'bytes'
```

**Comment by jerryneedell** [comment]
The example works after installing python3.6 on the Raspberry Pi.

**Comment by brentru** [comment]
@jerryneedell  Which version of python were you running on your Raspberry Pi?

**Comment by jerryneedell** [comment]
the default was 3.5.3 when I had the errors.

**Comment by brentru** [comment]
Tracking on branch: https://github.com/adafruit/io-client-python/tree/fix-typerror

**Comment by brentru** [comment]
This bug has been patched in master, closing...
