### ISSUE TITLE
Crash on REST API methods: receive_group, receive_next_group

### ISSUE THREAD

**Issue by brentru** [adafruit/io-client-python#70]
Command: `io.receive_group(created_group)`

Error Log:
>  Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/home/pi/.local/lib/python3.5/site-packages/Adafruit_IO/client.py", line 248, in receive_group
>     return Group.from_dict(self._get(path))
>   File "/home/pi/.local/lib/python3.5/site-packages/Adafruit_IO/client.py", line 91, in _get
>     self._handle_error(response)
>   File "/home/pi/.local/lib/python3.5/site-packages/Adafruit_IO/client.py", line 79, in _handle_error
>     raise RequestError(response)
> Adafruit_IO.errors.RequestError: Adafruit IO request failed: 404 Not Found - not found - API documentation can be found at https://io.adafruit.com/api/docs

Similar issue for next_group:

> f = aio.receive_next_group(house_group)
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/home/pi/.local/lib/python3.5/site-packages/Adafruit_IO/client.py", line 257, in receive_next_group
>     return Group.from_dict(self._get(path))
>   File "/home/pi/.local/lib/python3.5/site-packages/Adafruit_IO/client.py", line 91, in _get
>     self._handle_error(response)
>   File "/home/pi/.local/lib/python3.5/site-packages/Adafruit_IO/client.py", line 79, in _handle_error
>     raise RequestError(response)
> Adafruit_IO.errors.RequestError: Adafruit IO request failed: 404 Not Found - not found - API documentation can be found at https://io.adafruit.com/api/docs

**Comment by brentru** [comment]
**Edit:** 
These methods are legacy and should be removed:

- receive_next
- receive_group
- receive_previous_group
- receive_next_group
- receive_previous
