### ISSUE TITLE
Handle feed 404'ing if the feed does not exist

### ISSUE THREAD

**Issue by brentru** [adafruit/io-client-python#75]
This library currently 404's (feed not found) when a feed is referenced/assigned in the library, but not yet created:

> Traceback (most recent call last):
> File "/home/pi/io-client-python/examples/basics/temp_humidity.py", line 46, in <module>
> temperature_feed = aio.feeds('temperature')
> File "/home/pi/.local/lib/python3.5/site-packages/Adafruit_IO/client.py", line 241, in feeds
> return Feed.from_dict(self._get(path))
> File "/home/pi/.local/lib/python3.5/site-packages/Adafruit_IO/client.py", line 91, in _get
> self._handle_error(response)
> File "/home/pi/.local/lib/python3.5/site-packages/Adafruit_IO/client.py", line 79, in _handle_error
> raise RequestError(response)
> Adafruit_IO.errors.RequestError: Adafruit IO request failed: 404 Not Found - not found - API documentation can be found at https://io.adafruit.com/api/docs

We should check against the list of feeds to see if the feed exists. If it does not exist, create the feed.

I feel the best place to add this functionality is within client.py's `feeds` method, changing the functionality from:

>         """Retrieve a list of all feeds, or the specified feed.  If feed is not
>         specified a list of all feeds will be returned.  If feed is specified it
>         can be a feed name, key, or ID and the requested feed will be returned.
>         """

**to** 

>         """Retrieve a list of all feeds, or the specified feed.  If feed is not
>         specified a list of all feeds will be returned.  If feed is specified,
>          we'll check if the feed exists and the requeusted feed will be returned. 
>          If the feed does not exist, we'll call create_feed to create the specified feed.
>         """

**Comment by brentru** [comment]
Closing, don't auto-create feeds. Exception handling is the better route for this.
